// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

export interface Activity {
	id: string
	type: string // "habit_completed", "goal_created", "goal_completed", "article_saved"
	title: string
	description: string
	metadata?: string // JSON string for additional data
	userId: string
	createdAt: string
}

export interface ActivityResponse {
	data: Array<Activity>
	page: PageResponse
}

export interface Article {
	id: string
	title: string
	excerpt: string
	content: string
	category: string
	readTime: number
	imageUrl: string
	author: string
	publishedAt: string
	createdAt: string
	updatedAt: string
}

export interface ArticleRequest {
}
export interface ArticleRequestParams {
}

export interface ArticleResponse {
	data: Article
}

export interface ArticlesResponse {
	data: Array<Article>
	page: PageResponse
}

export interface AuthResponse {
	accessToken: string
	refreshToken: string
	expiresIn: number
	user: Profile
}

export interface Conversation {
	id: string
	title: string
	type: string // "coach" or "therapist"
	lastMessage: string
	userId: string
	createdAt: string
	updatedAt: string
}

export interface ConversationDetail {
	id: string
	title: string
	type: string
	messages: Array<Message>
	userId: string
	createdAt: string
	updatedAt: string
}

export interface ConversationDetailResponse {
	data: ConversationDetail
}

export interface ConversationRequest {
}
export interface ConversationRequestParams {
}

export interface ConversationResponse {
	data: Conversation
}

export interface ConversationsResponse {
	data: Array<Conversation>
	page: PageResponse
}

export interface CreateGoalRequest {
	title: string
	description: string
	category: string
	dueDate?: string
	relatedHabitIds?: Array<string>
}

export interface CreateHabitRequest {
	name: string
	description: string
	category: string
}

export interface EmptyResponse {
}

export interface GetMessagesRequest {
}
export interface GetMessagesRequestParams {
	page: number
	limit: number
}

export interface Goal {
	id: string
	title: string
	description: string
	category: string
	dueDate?: string
	progress: number
	completed: boolean
	relatedHabitIds?: Array<string>
	userId: string
	createdAt: string
	updatedAt: string
}

export interface GoalRequest {
}
export interface GoalRequestParams {
}

export interface GoalResponse {
	data: Goal
}

export interface GoalsResponse {
	data: Array<Goal>
	page: PageResponse
}

export interface Habit {
	id: string
	name: string
	description: string
	streak: number
	completed: boolean
	category: string
	userId: string
	createdAt: string
	updatedAt: string
}

export interface HabitRequest {
}
export interface HabitRequestParams {
}

export interface HabitResponse {
	data: Habit
}

export interface HabitsResponse {
	data: Array<Habit>
	page: PageResponse
}

export interface ListArticlesRequest {
}
export interface ListArticlesRequestParams {
	category?: string
	page: number
	limit: number
}

export interface ListConversationsRequest {
}
export interface ListConversationsRequestParams {
	type?: string // "coach" or "therapist"
	page: number
	limit: number
}

export interface LoginRequest {
	email: string
	password: string
}

export interface Message {
	id: string
	content: string
	role: string // "user" or "assistant"
	conversationId: string
	createdAt: string
}

export interface MessageResponse {
	data: Message
}

export interface MessagesResponse {
	data: Array<Message>
	page: PageResponse
}

export interface Notification {
	id: string
	title: string
	message: string
	type: string // "habit_reminder", "goal_deadline", "achievement", "system"
	read: boolean
	userId: string
	createdAt: string
}

export interface NotificationRequest {
}
export interface NotificationRequestParams {
}

export interface NotificationsResponse {
	data: Array<Notification>
	page: PageResponse
}

export interface PageRequest {
}
export interface PageRequestParams {
	page: number
	limit: number
}

export interface PageResponse {
	total: number
	page: number
	limit: number
	totalPages: number
}

export interface Profile {
	id: string
	fullName: string
	username: string
	email: string
	bio?: string
	location?: string
	website?: string
	interests?: Array<string>
	avatarUrl?: string
	createdAt: string
	updatedAt: string
}

export interface ProfileResponse {
	data: Profile
}

export interface RefreshRequest {
	refreshToken: string
}

export interface RegisterRequest {
	username: string
	email: string
	password: string
	fullName: string
}

export interface ReportRequest {
	type: string // "bug", "feedback", "abuse"
	title: string
	description: string
	email?: string
}

export interface SaveItemRequest {
	itemType: string
	itemId: string
}

export interface SavedItem {
	id: string
	itemType: string // "article", "goal", "habit"
	itemId: string
	userId: string
	createdAt: string
}

export interface SavedItemRequest {
}
export interface SavedItemRequestParams {
}

export interface SavedItemResponse {
	data: SavedItem
}

export interface SavedItemsResponse {
	data: Array<SavedItem>
	page: PageResponse
}

export interface SearchRequest {
}
export interface SearchRequestParams {
	q: string
	type?: string // "article", "goal", "habit", "conversation"
	page: number
	limit: number
}

export interface SearchResponse {
	data: Array<SearchResult>
	page: PageResponse
}

export interface SearchResult {
	id: string
	type: string // "article", "goal", "habit", "conversation"
	title: string
	description: string
	score: number
	highlight?: string
}

export interface SendMessageRequest {
	content: string
}

export interface Settings {
	id: string
	theme: string // "light", "dark", "system"
	language: string
	timezone: string
	emailNotifications: boolean
	pushNotifications: boolean
	habitReminders: boolean
	goalReminders: boolean
	userId: string
	createdAt: string
	updatedAt: string
}

export interface SettingsResponse {
	data: Settings
}

export interface StartConversationRequest {
	type: string // "coach" or "therapist"
	title?: string
	initialMessage?: string
}

export interface UpdateGoalRequest {
	title?: string
	description?: string
	category?: string
	dueDate?: string
	relatedHabitIds?: Array<string>
}

export interface UpdateHabitRequest {
	name?: string
	description?: string
	category?: string
}

export interface UpdateProfileRequest {
	fullName?: string
	bio?: string
	location?: string
	website?: string
	interests?: Array<string>
	avatarUrl?: string
}

export interface UpdateProgressRequest {
	progress: number
}

export interface UpdateSettingsRequest {
	theme?: string
	language?: string
	timezone?: string
	emailNotifications?: boolean
	pushNotifications?: boolean
	habitReminders?: boolean
	goalReminders?: boolean
}

